[
  {
    "name":"Gateway to the West",
    "hunt_id":"1",
    "city":"St. Louis",
    "art_focus":"3",
    "history_focus":"2",
    "culture_focus":"3",
    "difficulty_focus":"3",
    "state":"Missouri",
    "country":"USA",
    "starting_location":"48 N 4th St, St Louis, MO 63102, USA",
    "description":"Some may just pass through on their way to the west, but come see why St. Louis is worth sticking around for!",
    "distance_miles":"1.75",
    "lat":"38.625535",
    "long":"-90.188654",
    "huntPhotoURL":"https:\/\/www.scavengerhunt.com\/locations\/scavenger_hunt_photos\/featured\/st_louis_scavenger_hunt_St._Louis_Missouri_team_building_1524242695_thumb.jpg",
    "huntMediumPhotoURL":"https:\/\/www.scavengerhunt.com\/locations\/scavenger_hunt_photos\/featured\/st_louis_scavenger_hunt_St._Louis_Missouri_team_building_1524242695_medium.jpg",
    "huntLargePhotoURL":"https:\/\/www.scavengerhunt.com\/locations\/scavenger_hunt_photos\/featured\/st_louis_scavenger_hunt_St._Louis_Missouri_team_building_1524242695_large.jpg",
    "huntExtraLargePhotoURL":"https:\/\/www.scavengerhunt.com\/locations\/scavenger_hunt_photos\/featured\/st_louis_scavenger_hunt_St._Louis_Missouri_team_building_1524242695_extra_large.jpg",
    "total_reviews":"81",
    "url":"https:\/\/www.scavengerhunt.com\/locations\/st_louis_scavenger_hunt.html",
    "distance_from_user":"100000000000000000000000",
    "long_description":" They call St. Louis \u201cThe Gateway to the West\u201d but once you\u2019ve experienced this amazing city you won\u2019t ever want to leave. Parks and ballparks, magnificent courthouses and post office palaces, there's a lot to see on this epic scavenger hunt! You'll be helped along by Civil Rights heroes, a Disney favorite and a couple of Cardinals. It's time to strap on those walking shoes, round up some friends and book your St. Louis scavenger hunt today.",
    "star_rating":"4.54",
    "key":"0"
  },
  {
    "name":"Chicago Loop",
    "hunt_id":"2",
    "city":"Chicago",
    "art_focus":"2",
    "history_focus":"2",
    "culture_focus":"2",
    "difficulty_focus":"1",
    "state":"Illinois",
    "country":"USA",
    "starting_location":"78 E Washington St, Chicago, IL 60602, USA",
    "description":"You have never seen Chicago like this before! Race against the clock and get the highest score to win in the Windy City!",
    "distance_miles":"1.77",
    "lat":"41.88345043034215",
    "long":"-87.62496390000001",
    "huntPhotoURL":"https:\/\/www.scavengerhunt.com\/locations\/scavenger_hunt_photos\/featured\/Loop_Chicago_Scavenger_Hunt_Chicago_Illinois_team_building_1524242211_thumb.jpg",
    "huntMediumPhotoURL":"https:\/\/www.scavengerhunt.com\/locations\/scavenger_hunt_photos\/featured\/Loop_Chicago_Scavenger_Hunt_Chicago_Illinois_team_building_1524242211_medium.jpg",
    "huntLargePhotoURL":"https:\/\/www.scavengerhunt.com\/locations\/scavenger_hunt_photos\/featured\/Loop_Chicago_Scavenger_Hunt_Chicago_Illinois_team_building_1524242211_large.jpg",
    "huntExtraLargePhotoURL":"https:\/\/www.scavengerhunt.com\/locations\/scavenger_hunt_photos\/featured\/Loop_Chicago_Scavenger_Hunt_Chicago_Illinois_team_building_1524242211_extra_large.jpg",
    "total_reviews":"496",
    "url":"https:\/\/www.scavengerhunt.com\/locations\/Loop_Chicago_Scavenger_Hunt.html",
    "distance_from_user":"100000000000000000000000",
    "long_description":"Named for the cable car turnarounds and the prominent elevated railway that encircled the area at the end of the 19th century, the Loop is \r\nChicago's commercial and cultural core. On today's epic scavenger hunt of Chicago, you'll uncover the area's best sights and rich history. Along the way, you'll visit Cloud Gate, Art Institute of\r\n Chicago, and the Federal Reserve Bank of \r\nChicago. It's time to strap on those walking shoes, round up some friends and book your Chicago Loop scavenger hunt today!<\/p>","star_rating":"4.4","key":"1"
  }
]